### ISSUE TITLE
Janky Animation

### ISSUE THREAD

**Issue by binemmanuel** [landxcape/animated_marker#4]
Frames are skipped, when you increase the duration you'll notice it.

```dart
AnimatedMarker(
      animatedMarkers: markers.values.toSet(),
      duration: const Duration(milliseconds: 3000),
      curve: Curves.easeInOut,
      builder: (context, markers) {
        return GoogleMap(
          myLocationButtonEnabled: false,

          markers: markers,

          //
          initialCameraPosition: const CameraPosition(
            target: LatLng(.0, .0),
            zoom: 17,
          ),

          onMapCreated: onMapCreated,
        );
      },
);
```

https://github.com/user-attachments/assets/85bd5eaa-9ec5-4918-b545-31000e32a8be

**Comment by landxcape** [comment]
Hi, thanks for pointing out the issue. I have fixed it, but there are some things to note before I update it.
##### Reason for the janky behavior:
- The markers got a new location update before the animation could complete, so it jumped to the start of the new location.
##### Solution:
- Update the tween to take the "begin" of its position from the newly provided location to the position wherever it is in the animation.

So, now the duration can be longer than the update interval, but note that the marker will move to the newly updated position from the middle of an animation instead of jumping.

**Comment by binemmanuel** [comment]
The prompt response is greatly appreciated.
